# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2fcfbda5b9a23f314dfc1edf153586e1c4c3294a1346078a07a4ccdf994e785be23e45d60920c071aae4aeebdb9e6d09030751b7c8f963064bb423839939934

test:
  secret_key_base: 969ad6a7984f8d7b5fd14537f12a5c6345bc71a867f6244663390fee0bd5ff7cf5379c0a541733bd6da8925045aae824f796646a04330e12fd1e96a682fbd99b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
